/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AccessLogAggregates;
import com.konfigthis.client.model.AccessLogResultView;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccessLogServiceDetails
 */
public class AccessLogServiceDetailsTest {
    private final AccessLogServiceDetails model = new AccessLogServiceDetails();

    /**
     * Model tests for AccessLogServiceDetails
     */
    @Test
    public void testAccessLogServiceDetails() {
        // TODO: test AccessLogServiceDetails
    }

    /**
     * Test the property 'aggregates'
     */
    @Test
    public void aggregatesTest() {
        // TODO: test aggregates
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

}
