/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CompletePurchaseRequest
 */
public class CompletePurchaseRequestTest {
    private final CompletePurchaseRequest model = new CompletePurchaseRequest();

    /**
     * Model tests for CompletePurchaseRequest
     */
    @Test
    public void testCompletePurchaseRequest() {
        // TODO: test CompletePurchaseRequest
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'receipt'
     */
    @Test
    public void receiptTest() {
        // TODO: test receipt
    }

    /**
     * Test the property 'priceInLocalCurrency'
     */
    @Test
    public void priceInLocalCurrencyTest() {
        // TODO: test priceInLocalCurrency
    }

    /**
     * Test the property 'isoCurrencySymbol'
     */
    @Test
    public void isoCurrencySymbolTest() {
        // TODO: test isoCurrencySymbol
    }

}
