/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateTrialRestRequest
 */
public class CreateTrialRestRequestTest {
    private final CreateTrialRestRequest model = new CreateTrialRestRequest();

    /**
     * Model tests for CreateTrialRestRequest
     */
    @Test
    public void testCreateTrialRestRequest() {
        // TODO: test CreateTrialRestRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'strat'
     */
    @Test
    public void stratTest() {
        // TODO: test strat
    }

    /**
     * Test the property 'cohortType'
     */
    @Test
    public void cohortTypeTest() {
        // TODO: test cohortType
    }

    /**
     * Test the property 'cohorts'
     */
    @Test
    public void cohortsTest() {
        // TODO: test cohorts
    }

}
