/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateRoomRequest
 */
public class CreateRoomRequestTest {
    private final CreateRoomRequest model = new CreateRoomRequest();

    /**
     * Model tests for CreateRoomRequest
     */
    @Test
    public void testCreateRoomRequest() {
        // TODO: test CreateRoomRequest
    }

    /**
     * Test the property 'roomName'
     */
    @Test
    public void roomNameTest() {
        // TODO: test roomName
    }

    /**
     * Test the property 'keepSubscribed'
     */
    @Test
    public void keepSubscribedTest() {
        // TODO: test keepSubscribed
    }

    /**
     * Test the property 'players'
     */
    @Test
    public void playersTest() {
        // TODO: test players
    }

    /**
     * Test the property 'gameType'
     */
    @Test
    public void gameTypeTest() {
        // TODO: test gameType
    }

    /**
     * Test the property 'dbids'
     */
    @Test
    public void dbidsTest() {
        // TODO: test dbids
    }

}
