/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Era;
import com.konfigthis.client.model.IsoChronology;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocalDate
 */
public class LocalDateTest {
    private final LocalDate model = new LocalDate();

    /**
     * Model tests for LocalDate
     */
    @Test
    public void testLocalDate() {
        // TODO: test LocalDate
    }

    /**
     * Test the property 'dayOfYear'
     */
    @Test
    public void dayOfYearTest() {
        // TODO: test dayOfYear
    }

    /**
     * Test the property 'leapYear'
     */
    @Test
    public void leapYearTest() {
        // TODO: test leapYear
    }

    /**
     * Test the property 'chronology'
     */
    @Test
    public void chronologyTest() {
        // TODO: test chronology
    }

    /**
     * Test the property 'dayOfWeek'
     */
    @Test
    public void dayOfWeekTest() {
        // TODO: test dayOfWeek
    }

    /**
     * Test the property 'monthValue'
     */
    @Test
    public void monthValueTest() {
        // TODO: test monthValue
    }

    /**
     * Test the property 'dayOfMonth'
     */
    @Test
    public void dayOfMonthTest() {
        // TODO: test dayOfMonth
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'era'
     */
    @Test
    public void eraTest() {
        // TODO: test era
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

}
