/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CurrencyChange;
import com.konfigthis.client.model.ItemCreateRequest;
import com.konfigthis.client.model.Price;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PlayerOfferView
 */
public class PlayerOfferViewTest {
    private final PlayerOfferView model = new PlayerOfferView();

    /**
     * Model tests for PlayerOfferView
     */
    @Test
    public void testPlayerOfferView() {
        // TODO: test PlayerOfferView
    }

    /**
     * Test the property 'coupons'
     */
    @Test
    public void couponsTest() {
        // TODO: test coupons
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'buttonText'
     */
    @Test
    public void buttonTextTest() {
        // TODO: test buttonText
    }

    /**
     * Test the property 'titles'
     */
    @Test
    public void titlesTest() {
        // TODO: test titles
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'obtainItems'
     */
    @Test
    public void obtainItemsTest() {
        // TODO: test obtainItems
    }

    /**
     * Test the property 'obtainCurrency'
     */
    @Test
    public void obtainCurrencyTest() {
        // TODO: test obtainCurrency
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'descriptions'
     */
    @Test
    public void descriptionsTest() {
        // TODO: test descriptions
    }

    /**
     * Test the property 'obtain'
     */
    @Test
    public void obtainTest() {
        // TODO: test obtain
    }

}
