/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CreateRoomRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CreateRoomRequest {
  public static final String SERIALIZED_NAME_ROOM_NAME = "roomName";
  @SerializedName(SERIALIZED_NAME_ROOM_NAME)
  private String roomName;

  public static final String SERIALIZED_NAME_KEEP_SUBSCRIBED = "keepSubscribed";
  @SerializedName(SERIALIZED_NAME_KEEP_SUBSCRIBED)
  private Boolean keepSubscribed;

  public static final String SERIALIZED_NAME_PLAYERS = "players";
  @SerializedName(SERIALIZED_NAME_PLAYERS)
  private List<Integer> players = null;

  public static final String SERIALIZED_NAME_GAME_TYPE = "gameType";
  @SerializedName(SERIALIZED_NAME_GAME_TYPE)
  private String gameType;

  public static final String SERIALIZED_NAME_DBIDS = "dbids";
  @SerializedName(SERIALIZED_NAME_DBIDS)
  private List<Integer> dbids = null;

  public CreateRoomRequest() {
  }

  public CreateRoomRequest roomName(String roomName) {
    
    
    
    
    this.roomName = roomName;
    return this;
  }

   /**
   * Get roomName
   * @return roomName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoomName() {
    return roomName;
  }


  public void setRoomName(String roomName) {
    
    
    
    this.roomName = roomName;
  }


  public CreateRoomRequest keepSubscribed(Boolean keepSubscribed) {
    
    
    
    
    this.keepSubscribed = keepSubscribed;
    return this;
  }

   /**
   * Get keepSubscribed
   * @return keepSubscribed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getKeepSubscribed() {
    return keepSubscribed;
  }


  public void setKeepSubscribed(Boolean keepSubscribed) {
    
    
    
    this.keepSubscribed = keepSubscribed;
  }


  public CreateRoomRequest players(List<Integer> players) {
    
    
    
    
    this.players = players;
    return this;
  }

  public CreateRoomRequest addPlayersItem(Integer playersItem) {
    if (this.players == null) {
      this.players = new ArrayList<>();
    }
    this.players.add(playersItem);
    return this;
  }

   /**
   * Get players
   * @return players
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getPlayers() {
    return players;
  }


  public void setPlayers(List<Integer> players) {
    
    
    
    this.players = players;
  }


  public CreateRoomRequest gameType(String gameType) {
    
    
    
    
    this.gameType = gameType;
    return this;
  }

   /**
   * Get gameType
   * @return gameType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGameType() {
    return gameType;
  }


  public void setGameType(String gameType) {
    
    
    
    this.gameType = gameType;
  }


  public CreateRoomRequest dbids(List<Integer> dbids) {
    
    
    
    
    this.dbids = dbids;
    return this;
  }

  public CreateRoomRequest addDbidsItem(Integer dbidsItem) {
    if (this.dbids == null) {
      this.dbids = new ArrayList<>();
    }
    this.dbids.add(dbidsItem);
    return this;
  }

   /**
   * Get dbids
   * @return dbids
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getDbids() {
    return dbids;
  }


  public void setDbids(List<Integer> dbids) {
    
    
    
    this.dbids = dbids;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateRoomRequest instance itself
   */
  public CreateRoomRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRoomRequest createRoomRequest = (CreateRoomRequest) o;
    return Objects.equals(this.roomName, createRoomRequest.roomName) &&
        Objects.equals(this.keepSubscribed, createRoomRequest.keepSubscribed) &&
        Objects.equals(this.players, createRoomRequest.players) &&
        Objects.equals(this.gameType, createRoomRequest.gameType) &&
        Objects.equals(this.dbids, createRoomRequest.dbids)&&
        Objects.equals(this.additionalProperties, createRoomRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roomName, keepSubscribed, players, gameType, dbids, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRoomRequest {\n");
    sb.append("    roomName: ").append(toIndentedString(roomName)).append("\n");
    sb.append("    keepSubscribed: ").append(toIndentedString(keepSubscribed)).append("\n");
    sb.append("    players: ").append(toIndentedString(players)).append("\n");
    sb.append("    gameType: ").append(toIndentedString(gameType)).append("\n");
    sb.append("    dbids: ").append(toIndentedString(dbids)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("roomName");
    openapiFields.add("keepSubscribed");
    openapiFields.add("players");
    openapiFields.add("gameType");
    openapiFields.add("dbids");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("keepSubscribed");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateRoomRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateRoomRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateRoomRequest is not found in the empty JSON string", CreateRoomRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateRoomRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("roomName") != null && !jsonObj.get("roomName").isJsonNull()) && !jsonObj.get("roomName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `roomName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("roomName").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("players") != null && !jsonObj.get("players").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `players` to be an array in the JSON string but got `%s`", jsonObj.get("players").toString()));
      }
      if ((jsonObj.get("gameType") != null && !jsonObj.get("gameType").isJsonNull()) && !jsonObj.get("gameType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gameType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gameType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("dbids") != null && !jsonObj.get("dbids").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbids` to be an array in the JSON string but got `%s`", jsonObj.get("dbids").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateRoomRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateRoomRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateRoomRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateRoomRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateRoomRequest>() {
           @Override
           public void write(JsonWriter out, CreateRoomRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateRoomRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CreateRoomRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateRoomRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateRoomRequest
  * @throws IOException if the JSON string is invalid with respect to CreateRoomRequest
  */
  public static CreateRoomRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateRoomRequest.class);
  }

 /**
  * Convert an instance of CreateRoomRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

