/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MatchMakingRanking;
import com.konfigthis.client.model.MatchMakingWindowResp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * MatchMakingMatchesPvpResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class MatchMakingMatchesPvpResponse {
  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private String result;

  public static final String SERIALIZED_NAME_TOTAL_ENTRIES = "totalEntries";
  @SerializedName(SERIALIZED_NAME_TOTAL_ENTRIES)
  private Integer totalEntries;

  public static final String SERIALIZED_NAME_PLAYER_RANK = "playerRank";
  @SerializedName(SERIALIZED_NAME_PLAYER_RANK)
  private MatchMakingRanking playerRank;

  public static final String SERIALIZED_NAME_WINDOWS = "windows";
  @SerializedName(SERIALIZED_NAME_WINDOWS)
  private List<MatchMakingWindowResp> windows = null;

  public MatchMakingMatchesPvpResponse() {
  }

  public MatchMakingMatchesPvpResponse result(String result) {
    
    
    
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getResult() {
    return result;
  }


  public void setResult(String result) {
    
    
    
    this.result = result;
  }


  public MatchMakingMatchesPvpResponse totalEntries(Integer totalEntries) {
    
    
    
    
    this.totalEntries = totalEntries;
    return this;
  }

   /**
   * Get totalEntries
   * @return totalEntries
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getTotalEntries() {
    return totalEntries;
  }


  public void setTotalEntries(Integer totalEntries) {
    
    
    
    this.totalEntries = totalEntries;
  }


  public MatchMakingMatchesPvpResponse playerRank(MatchMakingRanking playerRank) {
    
    
    
    
    this.playerRank = playerRank;
    return this;
  }

   /**
   * Get playerRank
   * @return playerRank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MatchMakingRanking getPlayerRank() {
    return playerRank;
  }


  public void setPlayerRank(MatchMakingRanking playerRank) {
    
    
    
    this.playerRank = playerRank;
  }


  public MatchMakingMatchesPvpResponse windows(List<MatchMakingWindowResp> windows) {
    
    
    
    
    this.windows = windows;
    return this;
  }

  public MatchMakingMatchesPvpResponse addWindowsItem(MatchMakingWindowResp windowsItem) {
    if (this.windows == null) {
      this.windows = new ArrayList<>();
    }
    this.windows.add(windowsItem);
    return this;
  }

   /**
   * Get windows
   * @return windows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<MatchMakingWindowResp> getWindows() {
    return windows;
  }


  public void setWindows(List<MatchMakingWindowResp> windows) {
    
    
    
    this.windows = windows;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MatchMakingMatchesPvpResponse instance itself
   */
  public MatchMakingMatchesPvpResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchMakingMatchesPvpResponse matchMakingMatchesPvpResponse = (MatchMakingMatchesPvpResponse) o;
    return Objects.equals(this.result, matchMakingMatchesPvpResponse.result) &&
        Objects.equals(this.totalEntries, matchMakingMatchesPvpResponse.totalEntries) &&
        Objects.equals(this.playerRank, matchMakingMatchesPvpResponse.playerRank) &&
        Objects.equals(this.windows, matchMakingMatchesPvpResponse.windows)&&
        Objects.equals(this.additionalProperties, matchMakingMatchesPvpResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, totalEntries, playerRank, windows, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchMakingMatchesPvpResponse {\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    totalEntries: ").append(toIndentedString(totalEntries)).append("\n");
    sb.append("    playerRank: ").append(toIndentedString(playerRank)).append("\n");
    sb.append("    windows: ").append(toIndentedString(windows)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("result");
    openapiFields.add("totalEntries");
    openapiFields.add("playerRank");
    openapiFields.add("windows");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("totalEntries");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MatchMakingMatchesPvpResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!MatchMakingMatchesPvpResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchMakingMatchesPvpResponse is not found in the empty JSON string", MatchMakingMatchesPvpResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MatchMakingMatchesPvpResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("result") != null && !jsonObj.get("result").isJsonNull()) && !jsonObj.get("result").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `result` to be a primitive type in the JSON string but got `%s`", jsonObj.get("result").toString()));
      }
      // validate the optional field `playerRank`
      if (jsonObj.get("playerRank") != null && !jsonObj.get("playerRank").isJsonNull()) {
        MatchMakingRanking.validateJsonObject(jsonObj.getAsJsonObject("playerRank"));
      }
      if (jsonObj.get("windows") != null && !jsonObj.get("windows").isJsonNull()) {
        JsonArray jsonArraywindows = jsonObj.getAsJsonArray("windows");
        if (jsonArraywindows != null) {
          // ensure the json data is an array
          if (!jsonObj.get("windows").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `windows` to be an array in the JSON string but got `%s`", jsonObj.get("windows").toString()));
          }

          // validate the optional field `windows` (array)
          for (int i = 0; i < jsonArraywindows.size(); i++) {
            MatchMakingWindowResp.validateJsonObject(jsonArraywindows.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchMakingMatchesPvpResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchMakingMatchesPvpResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchMakingMatchesPvpResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchMakingMatchesPvpResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchMakingMatchesPvpResponse>() {
           @Override
           public void write(JsonWriter out, MatchMakingMatchesPvpResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchMakingMatchesPvpResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             MatchMakingMatchesPvpResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MatchMakingMatchesPvpResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MatchMakingMatchesPvpResponse
  * @throws IOException if the JSON string is invalid with respect to MatchMakingMatchesPvpResponse
  */
  public static MatchMakingMatchesPvpResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchMakingMatchesPvpResponse.class);
  }

 /**
  * Convert an instance of MatchMakingMatchesPvpResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

