/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Cohort;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Trial
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Trial {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ACTIVATED = "activated";
  @SerializedName(SERIALIZED_NAME_ACTIVATED)
  private Integer activated;

  public static final String SERIALIZED_NAME_COHORTS = "cohorts";
  @SerializedName(SERIALIZED_NAME_COHORTS)
  private List<Cohort> cohorts = null;

  public static final String SERIALIZED_NAME_CTYPE = "ctype";
  @SerializedName(SERIALIZED_NAME_CTYPE)
  private String ctype;

  public static final String SERIALIZED_NAME_SCHEDULE_START = "scheduleStart";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_START)
  private Integer scheduleStart;

  public static final String SERIALIZED_NAME_ASSIGNED = "assigned";
  @SerializedName(SERIALIZED_NAME_ASSIGNED)
  private Integer assigned;

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  private String strategy;

  public static final String SERIALIZED_NAME_TTYPE = "ttype";
  @SerializedName(SERIALIZED_NAME_TTYPE)
  private String ttype;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private Integer created;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public Trial() {
  }

  public Trial name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public Trial activated(Integer activated) {
    
    
    
    
    this.activated = activated;
    return this;
  }

   /**
   * Get activated
   * @return activated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getActivated() {
    return activated;
  }


  public void setActivated(Integer activated) {
    
    
    
    this.activated = activated;
  }


  public Trial cohorts(List<Cohort> cohorts) {
    
    
    
    
    this.cohorts = cohorts;
    return this;
  }

  public Trial addCohortsItem(Cohort cohortsItem) {
    if (this.cohorts == null) {
      this.cohorts = new ArrayList<>();
    }
    this.cohorts.add(cohortsItem);
    return this;
  }

   /**
   * Get cohorts
   * @return cohorts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Cohort> getCohorts() {
    return cohorts;
  }


  public void setCohorts(List<Cohort> cohorts) {
    
    
    
    this.cohorts = cohorts;
  }


  public Trial ctype(String ctype) {
    
    
    
    
    this.ctype = ctype;
    return this;
  }

   /**
   * Get ctype
   * @return ctype
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCtype() {
    return ctype;
  }


  public void setCtype(String ctype) {
    
    
    
    this.ctype = ctype;
  }


  public Trial scheduleStart(Integer scheduleStart) {
    
    
    
    
    this.scheduleStart = scheduleStart;
    return this;
  }

   /**
   * Get scheduleStart
   * @return scheduleStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getScheduleStart() {
    return scheduleStart;
  }


  public void setScheduleStart(Integer scheduleStart) {
    
    
    
    this.scheduleStart = scheduleStart;
  }


  public Trial assigned(Integer assigned) {
    
    
    
    
    this.assigned = assigned;
    return this;
  }

   /**
   * Get assigned
   * @return assigned
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getAssigned() {
    return assigned;
  }


  public void setAssigned(Integer assigned) {
    
    
    
    this.assigned = assigned;
  }


  public Trial strategy(String strategy) {
    
    
    
    
    this.strategy = strategy;
    return this;
  }

   /**
   * Get strategy
   * @return strategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStrategy() {
    return strategy;
  }


  public void setStrategy(String strategy) {
    
    
    
    this.strategy = strategy;
  }


  public Trial ttype(String ttype) {
    
    
    
    
    this.ttype = ttype;
    return this;
  }

   /**
   * Get ttype
   * @return ttype
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTtype() {
    return ttype;
  }


  public void setTtype(String ttype) {
    
    
    
    this.ttype = ttype;
  }


  public Trial created(Integer created) {
    
    
    
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCreated() {
    return created;
  }


  public void setCreated(Integer created) {
    
    
    
    this.created = created;
  }


  public Trial active(Boolean active) {
    
    
    
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    
    
    
    this.active = active;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Trial instance itself
   */
  public Trial putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trial trial = (Trial) o;
    return Objects.equals(this.name, trial.name) &&
        Objects.equals(this.activated, trial.activated) &&
        Objects.equals(this.cohorts, trial.cohorts) &&
        Objects.equals(this.ctype, trial.ctype) &&
        Objects.equals(this.scheduleStart, trial.scheduleStart) &&
        Objects.equals(this.assigned, trial.assigned) &&
        Objects.equals(this.strategy, trial.strategy) &&
        Objects.equals(this.ttype, trial.ttype) &&
        Objects.equals(this.created, trial.created) &&
        Objects.equals(this.active, trial.active)&&
        Objects.equals(this.additionalProperties, trial.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, activated, cohorts, ctype, scheduleStart, assigned, strategy, ttype, created, active, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trial {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    activated: ").append(toIndentedString(activated)).append("\n");
    sb.append("    cohorts: ").append(toIndentedString(cohorts)).append("\n");
    sb.append("    ctype: ").append(toIndentedString(ctype)).append("\n");
    sb.append("    scheduleStart: ").append(toIndentedString(scheduleStart)).append("\n");
    sb.append("    assigned: ").append(toIndentedString(assigned)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("    ttype: ").append(toIndentedString(ttype)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("activated");
    openapiFields.add("cohorts");
    openapiFields.add("ctype");
    openapiFields.add("scheduleStart");
    openapiFields.add("assigned");
    openapiFields.add("strategy");
    openapiFields.add("ttype");
    openapiFields.add("created");
    openapiFields.add("active");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("assigned");
    openapiRequiredFields.add("active");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Trial
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Trial.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Trial is not found in the empty JSON string", Trial.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Trial.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("cohorts") != null && !jsonObj.get("cohorts").isJsonNull()) {
        JsonArray jsonArraycohorts = jsonObj.getAsJsonArray("cohorts");
        if (jsonArraycohorts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("cohorts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `cohorts` to be an array in the JSON string but got `%s`", jsonObj.get("cohorts").toString()));
          }

          // validate the optional field `cohorts` (array)
          for (int i = 0; i < jsonArraycohorts.size(); i++) {
            Cohort.validateJsonObject(jsonArraycohorts.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("ctype") != null && !jsonObj.get("ctype").isJsonNull()) && !jsonObj.get("ctype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ctype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ctype").toString()));
      }
      if ((jsonObj.get("strategy") != null && !jsonObj.get("strategy").isJsonNull()) && !jsonObj.get("strategy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `strategy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("strategy").toString()));
      }
      if ((jsonObj.get("ttype") != null && !jsonObj.get("ttype").isJsonNull()) && !jsonObj.get("ttype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ttype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ttype").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Trial.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Trial' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Trial> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Trial.class));

       return (TypeAdapter<T>) new TypeAdapter<Trial>() {
           @Override
           public void write(JsonWriter out, Trial value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Trial read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Trial instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Trial given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Trial
  * @throws IOException if the JSON string is invalid with respect to Trial
  */
  public static Trial fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Trial.class);
  }

 /**
  * Convert an instance of Trial to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

