/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AttachmentRequest;
import com.konfigthis.client.model.CreateMessageCampaignRequest;
import com.konfigthis.client.model.EjectMessageCampaignRequest;
import com.konfigthis.client.model.EmptyResponse;
import com.konfigthis.client.model.GetCampaignsResponse;
import com.konfigthis.client.model.RescheduleMessageCampaignRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CampaignApi
 */
@Disabled
public class CampaignApiTest {

    private static CampaignApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CampaignApi(apiClient);
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewLegacyCloudCampaignTest() throws ApiException {
        Boolean resendToPastRecipients = null;
        Integer sent = null;
        String mtype = null;
        String mbStore = null;
        String mbExpiration = null;
        String name = null;
        String subject = null;
        String mbEntSpec = null;
        Integer mbEntQuant = null;
        String datepoint = null;
        List<AttachmentRequest> mbAttachments = null;
        String recur = null;
        String msg = null;
        List<String> rules = null;
        String mbEnt = null;
        String start = null;
        String days = null;
        EmptyResponse response = api.createNewLegacyCloudCampaign(resendToPastRecipients, sent)
                .mtype(mtype)
                .mbStore(mbStore)
                .mbExpiration(mbExpiration)
                .name(name)
                .subject(subject)
                .mbEntSpec(mbEntSpec)
                .mbEntQuant(mbEntQuant)
                .datepoint(datepoint)
                .mbAttachments(mbAttachments)
                .recur(recur)
                .msg(msg)
                .rules(rules)
                .mbEnt(mbEnt)
                .start(start)
                .days(days)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLegacyCloudCampaignsTest() throws ApiException {
        GetCampaignsResponse response = api.getLegacyCloudCampaigns()
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeLegacyCloudTest() throws ApiException {
        String sid = null;
        EmptyResponse response = api.removeLegacyCloud()
                .sid(sid)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateScheduleTest() throws ApiException {
        String sid = null;
        String startDate = null;
        EmptyResponse response = api.updateSchedule()
                .sid(sid)
                .startDate(startDate)
                .execute();
        // TODO: test validations
    }

}
