/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CodeClaimRequest;
import com.konfigthis.client.model.CodeCreateRequest;
import com.konfigthis.client.model.CodeRedemptionResponse;
import com.konfigthis.client.model.CreateRedemptionDef;
import com.konfigthis.client.model.GetAvailableCodesResponse;
import com.konfigthis.client.model.GetDefinitionsResponse;
import com.konfigthis.client.model.ImportCodesRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PromoApi
 */
@Disabled
public class PromoApiTest {

    private static PromoApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PromoApi(apiClient);
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void claimLegacyPromoTest() throws ApiException {
        String code = null;
        CodeRedemptionResponse response = api.claimLegacyPromo()
                .code(code)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createLegacyPromoTest() throws ApiException {
        Integer codes = null;
        Integer claimsPerCode = null;
        CreateRedemptionDef definition = null;
        CodeRedemptionResponse response = api.createLegacyPromo(codes, claimsPerCode)
                .definition(definition)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generatePromoCodeTest() throws ApiException {
        Integer definitionId = null;
        Integer claimsPerCode = null;
        List<String> codes = null;
        CodeRedemptionResponse response = api.generatePromoCode(definitionId, claimsPerCode)
                .codes(codes)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLegacyPromosTest() throws ApiException {
        GetDefinitionsResponse response = api.getLegacyPromos()
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPromoCodesTest() throws ApiException {
        Integer id = null;
        GetAvailableCodesResponse response = api.getPromoCodes(id)
                .execute();
        // TODO: test validations
    }

}
