/*
 * history basic
 * var Beamable = BeamContext.Default; - That one line of code is a gateway to everything you need to build custom server logic via microservices along with a world of LiveOps tools and live services to build games that players love.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.FacebookPaymentUpdateRequest;
import com.konfigthis.client.model.FacebookPaymentUpdateResponse;
import com.konfigthis.client.model.FacebookUpdatedEntry;
import com.konfigthis.client.model.SubscriptionVerificationResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UpdateApi
 */
@Disabled
public class UpdateApiTest {

    private static UpdateApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new UpdateApi(apiClient);
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookPaymentsUpdateTest() throws ApiException {
        String hubMode = null;
        String hubChallenge = null;
        String hubVerifyToken = null;
        SubscriptionVerificationResponse response = api.facebookPaymentsUpdate()
                .hubMode(hubMode)
                .hubChallenge(hubChallenge)
                .hubVerifyToken(hubVerifyToken)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookPaymentsUpdate_0Test() throws ApiException {
        String _object = null;
        List<FacebookUpdatedEntry> entry = null;
        FacebookPaymentUpdateResponse response = api.facebookPaymentsUpdate_0()
                ._object(_object)
                .entry(entry)
                .execute();
        // TODO: test validations
    }

}
